language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - example-runner/example-repos
node_js:
  - '9'
  - '8'
script:
  - yarn test
  - yarn build
  - yarn benchmark
  - yarn run-examples
