language: node_js
# Theoretically we could cache node_modules and example-repos, but those end up
# being very slow to download and are largely duplicated with yarn cache.
cache:
  yarn: true
# Don't do feature branch builds; we only need one build per PR.
branches:
  only:
    - "master"
before_install:
  - npm install -g yarn@latest
jobs:
  include:
    # Put the slowest builds first, since they are more likely to start first
    - node_js: '12'
      script:
        - yarn fast-build
        - yarn run-examples babel
    - node_js: '12'
      script:
        - yarn fast-build
        - yarn run-examples react decaffeinate decaffeinate-parser coffee-lex
    - node_js: '12'
      script:
        - yarn fast-build
        - yarn run-examples tslint apollo-client
    - node_js: '12'
      script:
        - yarn build
        - yarn lint
        - yarn test-with-coverage && yarn report-coverage
        - yarn test262
    - node_js: '10'
      script:
        - yarn build
        - yarn test-only
