#!/usr/bin/env bash

set -e

TSC="${TSC:-node_modules/.bin/tsc}"

# The build dir has all build artifacts, including the benchmark. The dist dir
# is the subset that's shipped as part of the package.
mkdir -p ./build
mkdir -p ./dist

echo 'Building ES module version.'
"${TSC}" \
  --project . \
  --outDir build \
  --module ES2015 \
  --moduleResolution node

for js in $(find build -name '*.js'); do
  mv "${js}" "$(dirname "${js}")/$(basename "${js}" .js).mjs"
done

echo 'Building CommonJS version.'
"${TSC}" \
  --project . \
  --outDir build \
  --module commonjs \
  --moduleResolution node

cp -r build/src dist
cp -r build/sucrase-babylon dist

echo 'Building @sucrase/gulp-plugin'
cd ./integrations/gulp-plugin
yarn
cd ../..

"${TSC}" \
  --project ./integrations/gulp-plugin \
  --outDir ./integrations/gulp-plugin/dist \
  --module commonjs \
  --moduleResolution node
