#!/usr/bin/env bash

set -e

TSC="${TSC:-node_modules/.bin/tsc}"

# The build dir has all build artifacts, including the benchmark. The dist dir
# is the subset that's shipped as part of the package.
mkdir -p ./build

echo 'Building ES module version.'
"${TSC}" \
  --project . \
  --outDir build \
  --module ES2015 \
  --moduleResolution node

for js in $(find build -name '*.js'); do
  mv "${js}" "$(dirname "${js}")/$(basename "${js}" .js).mjs"
done

echo 'Building CommonJS version.'
"${TSC}" \
  --project . \
  --outDir build \
  --module commonjs \
  --moduleResolution node

rm -rf ./dist
cp -r build/src dist

echo 'Building @sucrase/gulp-plugin'
cd ./integrations/gulp-plugin
yarn
cd ../..

"${TSC}" \
  --project ./integrations/gulp-plugin \
  --outDir ./integrations/gulp-plugin/dist \
  --module commonjs \
  --moduleResolution node

echo 'Building @sucrase/webpack-loader'
cd ./integrations/webpack-loader
yarn
cd ../..

"${TSC}" \
  --project ./integrations/webpack-loader \
  --outDir ./integrations/webpack-loader/dist \
  --module commonjs \
  --moduleResolution node

echo 'Building @sucrase/webpack-object-rest-spread-plugin'
cd ./integrations/webpack-object-rest-spread-plugin
yarn
cd ../..

"${TSC}" \
  --project ./integrations/webpack-object-rest-spread-plugin \
  --outDir ./integrations/webpack-object-rest-spread-plugin/dist \
  --module commonjs \
  --moduleResolution node

echo 'Building @sucrase/jest-plugin'
cd ./integrations/jest-plugin
yarn
cd ../..

"${TSC}" \
  --project ./integrations/jest-plugin \
  --outDir ./integrations/jest-plugin/dist \
  --module commonjs \
  --moduleResolution node
