#!/usr/bin/env bash

set -e

OUT_DIR="${OUT_DIR:-./build}"

# The build dir has all build artifacts, including the benchmark. The dist dir
# is the subset that's shipped as part of the package.
rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}"

echo 'Building CommonJS version.'
bin/sucrase ./src -d "${OUT_DIR}/src" --transforms imports,typescript
bin/sucrase ./test -d "${OUT_DIR}/test" --transforms imports,typescript
bin/sucrase ./benchmark -d ${OUT_DIR}/benchmark --transforms imports,typescript

rm -rf ./dist
cp -r build/src dist
