#!/usr/bin/env bash

set -e

OUT_DIR="${OUT_DIR:-./build}"

# The build dir has all build artifacts, including the benchmark. The dist dir
# is the subset that's shipped as part of the package.
rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}"

echo 'Building CommonJS version.'
bin/sucrase ./src -d "${OUT_DIR}/src" --transforms imports,typescript
bin/sucrase ./test -d "${OUT_DIR}/test" --transforms imports,typescript
bin/sucrase ./benchmark -d build/benchmark --transforms imports,typescript

echo 'Building Babylon fork.'
bin/sucrase sucrase-babylon -d "${OUT_DIR}/sucrase-babylon" --transforms imports,flow

rm -rf ./dist
mkdir -p ./dist
cp -r build/src dist
cp -r build/sucrase-babylon dist
