name: "All tests"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    name: "Lint and core tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn test-with-coverage && yarn report-coverage
      - run: yarn test262
  test-older-node:
    name: "Test on older node versions"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - node_version: '10'
          - node_version: '12'
          - node_version: '14'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: yarn
      - run: yarn build
      - run: yarn test-only
  test-examples:
    name: "Test example projects"
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include:
          - projects: "babel"
          - projects: "react decaffeinate decaffeinate-parser coffee-lex"
          - projects: "tslint apollo-client"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: yarn
      - run: yarn fast-build
      - run: yarn run-examples ${{ matrix.projects }}
  perf-benchmark:
    name: "Compare performance"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch all branches so we can compare with the default branch.
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: yarn
      # Clone the jest repo and run an untimed benchmark first, since the first
      # run immediately after cloning tends to be slower.
      - run: yarn benchmark jest-dev
      - run: yarn benchmark-compare
      # The benchmark-compare script leaves a ./.perf-comparison/summary.txt file
      # to be forwarded to the comment-perf.yml workflow via an artifact. We
      # also need to send the PR number. See that file and 
      # https://securitylab.github.com/research/github-actions-preventing-pwn-requests
      # for details of how the two fit together.
      - run: echo ${{ github.event.number }} > ./.perf-comparison/pr-number.txt
      - uses: actions/upload-artifact@v2
        with:
          name: perf-comparison
          path: .perf-comparison/
